### ISSUE TITLE
does not work with node-version-manager

### ISSUE THREAD

**Issue by noahpeters** [luscus/package.root#1]
there is a package.json file in the .nvm folder that package.root thinks makes this the package root.

```
fs.js:945
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/npeters/.nvm/node_modules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at Object.list (/Users/npeters/.nvm/versions/node/v6.2.2/lib/node_modules/sl-em7-ap2/node_modules/package.loader/lib/tools/dependencies.js:13:20)
    at inspect (/Users/npeters/.nvm/versions/node/v6.2.2/lib/node_modules/sl-em7-ap2/node_modules/package.loader/lib/tools/crawler.js:73:36)
    at crawl (/Users/npeters/.nvm/versions/node/v6.2.2/lib/node_modules/sl-em7-ap2/node_modules/package.loader/lib/tools/crawler.js:35:13)
    at Object.<anonymous> (/Users/npeters/.nvm/versions/node/v6.2.2/lib/node_modules/sl-em7-ap2/node_modules/package.loader/lib/tools/crawler.js:82:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by luscus** [comment]
had some issues with my mails at that time... didn't see the issue coming in.
I will fix this today
